### PR TITLE
Streaming read for huge log files (> 1GB) (#18)

### PR DESCRIPTION
**Pull request by pbadenski**
Add support for very large files (#18)

### CODE REVIEW

**Comment by pbadenski** [comment]
@thlorenz anything else I can do to help speed up this merge? 😄

**Comment by pbadenski** [comment]
@tholrenz just following up on the above, is there anything I can do to help getting this pull request through to master?

**Comment by thlorenz** [comment]
Wow so sorry for not responding earlier.
This looks great!

As long as this doesn't break existing functionality I'm fine merging this.

So I made you collaborator.

Please merge to master following [this guide](https://gist.github.com/thlorenz/f7df0daf13c6f6c1fa84).
I will then version and publish to npm.

Thanks!

**Comment by pbadenski** [comment]
Awesome, will do - thanks!

**Comment by pbadenski** [comment]
Done

**Comment by thlorenz** [comment]
Awesome, published as `0.6.0`, huge 🙏

**Pull request closed without merging**
